name: PowerCat CI/CD

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'   
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Pester Tests
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -Force -Scope CurrentUser

      - name: Run Pester tests
        shell: pwsh
        run: |
          Import-Module -Name Pester -Force  
          Invoke-Pester -Path tests -Output Detailed

  publish:
    name: Publish to PSGallery
    needs: test
    runs-on: windows-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Validate module manifest
        shell: pwsh
        run: Test-ModuleManifest -Path .\src\powerCat\powerCat.psd1

      - name: Publish module to PSGallery
        shell: pwsh
        run: Publish-Module -Path .\src\powerCat -NuGetApiKey $env:PSGALLERY_KEY -Verbose
        env:
          PSGALLERY_KEY: ${{ secrets.PSGALLERY_KEY }}
